version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_1104Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: SIQAJDBCAdapterTests
  version: "1.0"
  gitServerName: MJANGit
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: DADA_GlobalVariable1
  version: "1.0"
  gitServerName: MJANGit
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: SIQACloudStreamsTests
  version: "1.0"
  gitServerName: MJANGit
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
- name: SIQA_TimeoutTest
  gitServerName: MJANGit
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
